### ISSUE TITLE
SASS Version of the Project

### ISSUE THREAD

**Issue by douglasdeodato** [ITinDublin/ITinDublin.github.io#12]
Logo logo estarei convertendo todo css para .scss, se alguem tiver conhecimento e puder ajudar por favor ajude :)

obrigado.

**Comment by wpolicarpo** [comment]
@douglasdeodato posso ajudar na conversão mais pro final dessa semana.

**Comment by douglasdeodato** [comment]
cool, mais na verdade nem comecei lol, mais quero seguir essa estrutura aqui que eu inveitei, eu estudei pra caralho pra chegar nessa versao, vendo projetos BEM e smacss veja ae: https://github.com/douglasdeodato/lovelycss/tree/master/scss
