### ISSUE TITLE
Pagina Wiki

### ISSUE THREAD

**Issue by douglasdeodato** [ITinDublin/ITinDublin.github.io#16]
Oi @lffsantos  vi que voce comecou a fazer a pagina wiki entao como sera alimentado essa pagina? vai ser estatica json bd? n'os temos um projeto chamado: https://github.com/ITinDublin/wiki-it-irlanda-br  voce quer descontinuar ele e jogar tudo aqui mesmo?  qual sua opniao.

@wpolicarpo que acha?

valeu galera

**Comment by lffsantos** [comment]
então, hoje esta tudo estático, 
funciona assim... o usuário cria uma página aqui..
[https://github.com/ITinDublin/ITinDublin.github.io/tree/develop/content/pages/wiki](https://github.com/ITinDublin/ITinDublin.github.io/tree/develop/content/pages/wiki)
e faz a solicitação de um PR... dai ela vai aparecer aqui..
https://itindublin.github.io/wiki

Dessa forma esse outro projeto [wiki-it-irlanda-br](https://github.com/ITinDublin/wiki-it-irlanda-br) morreria... ou então poderíamos salvar as páginas da wiki nesse projeto [wiki-it-irlanda-br](https://github.com/ITinDublin/wiki-it-irlanda-br) e dar um jeito de ler elas a partir daqui.

Eu acho que por enquanto poderíamos manter aqui nesse projeto mesmo.

**Comment by douglasdeodato** [comment]
show entao,  podemos manter tudo em um projeto so entao. me fala quando voce migrar, pq decontinuarei o projeto.

la nao tem muita coisa mesmo, creio que 2 paginas.

me fala ae entao.

abraco.

**Comment by wpolicarpo** [comment]
@douglasdeodato @lffsantos acho uma boa migrarmos tudo pra cá. Podemos pegar o conteúdo que tem lá e jogar aqui.

Eu vou agitar a compra de um domínio para colocar isso no ar de forma "oficial" na semana que vem, pois não estou em Dublin essa semana.

**Comment by douglasdeodato** [comment]
@wpolicarpo  show perfeito.
