### ISSUE TITLE
Incorporar um editor Markdown no Site?

### ISSUE THREAD

**Issue by lffsantos** [ITinDublin/ITinDublin.github.io#18]
Será que seria  bom colocar um editor incorporado ao site?
acredito que muitas pessoas tem problemas para escrever no formato MD(apesar de inúmeros editores online) talvez facilitaria a criação dos arquivos na wiki?  
ex:  [https://simplemde.com/](https://simplemde.com/)

**Comment by douglasdeodato** [comment]
logico creio que sim, mais como funcionaria isso? digo como o cara poderia editar os arquivo? ele teria que ter uma permissao para isso? correto?

**Comment by lffsantos** [comment]
então, a versão inicial, seria somente para ele ter um ambiente para escrever e depois copiar e colar em um arquivo que ele criar.
em um segundo momento, poderíamos criar um serviço que faria isso, eu já tenho algumas ideias.

**Comment by douglasdeodato** [comment]
show, existem outros plugins e programs que fazem isso tambem, enfim sua ideia 'e altamente valida.

**Comment by wpolicarpo** [comment]
Acho bacana, mas acho que poderíamos usar o próprio github pra isso. Aqui já é possível adicionar um arquivo e tem o preview do markdown. Não sei se estaríamos reinventando a roda.

**Comment by lffsantos** [comment]
É já tem umas opções online e o próprio git para ajudar nisso.
Mas acho que tem muita gente que não vai contribuir ou porque não tem github ou por não querer fazer o processo Fork/PR. (o que é uma pena)
Com uma opção no site encorajaria mais as pessoas, a contribuir, eu acho.
mas isso pode ser feito mais pra frente.

**Comment by douglasdeodato** [comment]
eu cho que deveriamos resolver isso da maneira mais facil, google docs? com permissao? que acham? ae depois a gente transfere isso

**Comment by douglasdeodato** [comment]
@wpolicarpo @lffsantos @victoraldir

**Comment by victoraldir** [comment]
O editor seria bacana. Mas acho que comecar fazendo isso manualmente docs -> artigo.md, a principio, seria mais interessante para termos uma ideia de qual sera o engajamento.

**Comment by lffsantos** [comment]
Acho que a maneira mais fácil no momento seria aqui no git mesmo, caso a pessoa não queira ter o trabalho de fazer o PR, poderíamos sugerir para ele criar uma issue, e colar o conteúdo dele no formato MD que dai colocamos colocamos la.

**Comment by douglasdeodato** [comment]
isso @lffsantos  isso ta ate descrito na readme. criar uma issue

**Comment by wpolicarpo** [comment]
@douglasdeodato você ainda é membro dessa org?
