### ISSUE TITLE
Codigo fonte em ingles ou portugues?

### ISSUE THREAD

**Issue by victoraldir** [ITinDublin/ITinDublin.github.io#20]
Hey all,
Sugiro ressaltar isso no segmento de contribuicao do readme a fim de evitar refactory de artefatos e codigo no futuro.

**Comment by douglasdeodato** [comment]
nao entendi muito bem.

**Comment by victoraldir** [comment]
@douglasdeodato fiz o fork do projeto e tava dando uma olhada na estrutura. 

Vi esse tipo de situacao.

<img width="985" alt="screen shot 2016-10-12 at 16 51 29" src="https://cloud.githubusercontent.com/assets/881964/19317253/56de26b2-909c-11e6-889b-1e1edd00a9fc.png">

So achei que seria interessante criar artefatos em 1 lingua so

Abraco

**Comment by douglasdeodato** [comment]
@victoraldir  ah entendi, seria legal abrir o topico em relacao a isso que acha? gostaria de abrir um topico de discussao sobre isso?  valeu abraco

**Comment by lffsantos** [comment]
@victoraldir boa observação...
em relação as pastas o pelican utiliza o inglês(articles, content, pages) é estrutura dele..
quanto as outras pastas que criamos podemos seguir o mesmo padrão...em ingês tb, acredito que ficara melhor mesmo.

**Comment by wpolicarpo** [comment]
English, please :)

**Comment by victoraldir** [comment]
Voto por ingles tb. =)

**Comment by lffsantos** [comment]
É concordo tb...
vamos padronizar..p inglês então
nomes:
Pastas: EN
Arquivos(CSS/JS) EN
os arquivos markdown acho que fica em PT msm, e colocar essa info em algum lugar no readme.

**Style Guide**

**Comment by douglasdeodato** [comment]
@victoraldir  tipo eu sempre uso ingles, mais o que esta acontecendo 'e que como o projeto 'e brasileiro as vezes da essa misturada hahahah, mais vamos pro english entao.
