### ISSUE TITLE
Dúvida sobre o Slack

### ISSUE THREAD

**Issue by goenning** [ITinDublin/ITinDublin.github.io#3]
Acabei de ver no site que o grupo tem um Slack.
Ele é privado? Se não for, qual o link de registro?

**Comment by lffsantos** [comment]
Boa @goenning ... pesquisando no grupo do [facebook](https://www.facebook.com/groups/345245825571836/for_sale_search/?forsalesearchtype=all&query=slack&referral_surface=direct_link&availability=available) encontrei esse link...
[https://itindublin.herokuapp.com/](https://itindublin.herokuapp.com/)

Se quiser ajudar ... seria legal criar uma página na wiki informando como fazer para se registrar no slack do grupo , assim na página [https://itindublin.github.io/wiki](https://itindublin.github.io/wiki) poderia realizar uma busca e encontrar a informação.

[https://itindublin.github.io/como-contribuir-com-a-wiki](https://itindublin.github.io/como-contribuir-com-a-wiki)

**Comment by goenning** [comment]
Na minha opinião trocando o link de https://itindublin.slack.com/ por https://itindublin.herokuapp.com/ é suficiente. Se cadastrar no Slack é next, next, finish. Só precisa ter a URL correta.

**Comment by lffsantos** [comment]
alterado neste PR: #4
