### ISSUE TITLE
Página de Eventos

### ISSUE THREAD

**Issue by lffsantos** [ITinDublin/ITinDublin.github.io#6]
Página para a divulgação dos eventos da comunidade.

https://itindublin.github.io/eventos

**Comment by douglasdeodato** [comment]
teriamos que ver uma forma de linkar essa pagina com a de eventos do facebook, assim ela estaria sempre atualizada sem precisar atualizacao. que acha?  @wpolicarpo ?

**Comment by wpolicarpo** [comment]
Eu acho que os eventos são privados, não sei como fazer. Mas vale dar uma pesquisada.

**Comment by douglasdeodato** [comment]
:+1:

**Comment by lffsantos** [comment]
Outra opção seria criarmos os eventos no [https://www.meetup.com](https://www.meetup.com)
Criamos um grupo la e dai passamos a usar ele para registrar os eventos...
ex: https://www.meetup.com/pt-BR/pythonireland/

Eles tem uma api rest bacana, poderiamos consumir ela e pegar o eventos. [https://www.meetup.com/pt-BR/meetup_api/](https://www.meetup.com/pt-BR/meetup_api/)

Poderamos ter uma lista com os grupos de meetup de TI em dublin que poderiam ser cadastrados pelo usuário em uma planilha... de posse desse nome era sé ler a planilha pegar os eventos de cada grupo e listar na página.

Ex:
-/eventos/grupos-meetup.json

**Comment by wpolicarpo** [comment]
Eu não conheço a API do FB, mas nós conseguimos listar os eventos do grupo usando o SDK JS deles:

``` javascript
FB.api("/345245825571836/events", function (response) {
  console.log(response)
});
```

Testem aqui: https://developers.facebook.com/tools/console/

O problema é que precisamos de um token para autenticação. Talvez o cara tenha que dar permissão para podermos usar o token dele (só quem tiver no grupo terá acesso à essa lista, imagino).

**Comment by lffsantos** [comment]
A api do meetup não precisa de autenticação:
- https://secure.meetup.com/meetup_api/console/?_locale=pt-BR

https://secure.meetup.com/meetup_api/console/?path=/:urlname/events
https://secure.meetup.com/meetup_api/console/?path=/2/members
