### ISSUE TITLE
criar label para issues

### ISSUE THREAD

**Issue by lffsantos** [ITinDublin/ITinDublin.github.io#9]
@wpolicarpo @paulera  acho que seria legal criar umas labels para classificar as issues...

algo como: 
-Dúvidas
-Bug
-Melhoria
-Pergunta

**Comment by wpolicarpo** [comment]
Acho que os labels default do gh já atendem, não? Se não atenderem completamente, podemos ir adicionando de acordo com a necessidade.

**Comment by lffsantos** [comment]
é verdade, só tem q ter permissão pra colocar

**Comment by douglasdeodato** [comment]
@wpolicarpo  da permissao pro @lffsantos  facilita a vida do rapaz :) :+1:

**Comment by wpolicarpo** [comment]
@lffsantos feito! /cc @douglasdeodato
